# Generated by Django 4.1.3 on 2023-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_client_datenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Nif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='telephone'),
        ),
    ]
