# Generated by Django 4.1.3 on 2023-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_client_nif_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Nif',
            field=models.IntegerField(default=0, verbose_name='Nif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(default=0, verbose_name='telephone'),
        ),
    ]
